In [1]:
import numpy as np
import pandas as pd

In [44]:
# primero cargamos el dataset
prospects_stage = pd.read_csv('/content/drive/My Drive/Colab Notebooks/data_sets/Entrenamieto_ECI_2020.csv')

In [45]:
# y hacemos una inspecci√≥n inicial viusal de los datos
prospects_stage.head()

      ID    Region  ...        Stage       Prod_Category_A
0  27761      EMEA  ...  Closed Lost  Prod_Category_A_None
1  27760      EMEA  ...   Closed Won  Prod_Category_A_None
2  27446  Americas  ...   Closed Won  Prod_Category_A_None
3  16808  Americas  ...  Closed Lost  Prod_Category_A_None
4  16805  Americas  ...  Closed Lost  Prod_Category_A_None

[5 rows x 52 columns]

In [46]:
# y luego una mas detallas de tipos para identificar los tipos que asigno automaticamente el parser de pandas
prospects_stage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16947 entries, 0 to 16946
Data columns (total 52 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   ID                                  16947 non-null  int64
 1   Region                              16947 non-null  object
 2   Territory                           16947 non-null  object
 3   Pricing, Delivery_Terms_Quote_Appr  16947 non-null  int64
 4   Pricing, Delivery_Terms_Approved    16947 non-null  int64
 5   Bureaucratic_Code_0_Approval        16947 non-null  int64
 6   Bureaucratic_Code_0_Approved        16947 non-null  int64
 7   Submitted_for_Approval              16947 non-null  int64
 8   Bureaucratic_Code                   16947 non-null  object
 9   Account_Created_Date                16947 non-null  object
 10  Source                              16947 non-null  object
 11  Billing_Country                     16947 non-null  object
 12  Account_Name                        16947 non-null  object
 13  Opportunity_Name                    16947 non-null  object
 14  Opportunity_ID                      16947 non-null  int64
 15  Sales_Contract_No                   16947 non-null  object
 16  Account_Owner                       16947 non-null  object
 17  Opportunity_Owner                   16947 non-null  object
 18  Account_Type                        16947 non-null  object
 19  Opportunity_Type                    16947 non-null  object
 20  Quote_Type                          16947 non-null  object
 21  Delivery_Terms                      16947 non-null  object
 22  Opportunity_Created_Date            16947 non-null  object
 23  Brand                               16947 non-null  object
 24  Product_Type                        16947 non-null  object
 25  Size                                16947 non-null  object
 26  Product_Category_B                  16947 non-null  object
 27  Price                               16947 non-null  object
 28  Currency                            16947 non-null  object
 29  Last_Activity                       16947 non-null  object
 30  Quote_Expiry_Date                   16947 non-null  object
 31  Last_Modified_Date                  16947 non-null  object
 32  Last_Modified_By                    16947 non-null  object
 33  Product_Family                      16947 non-null  object
 34  Product_Name                        16947 non-null  object
 35  ASP_Currency                        16947 non-null  object
 36  ASP                                 13738 non-null  float64
 37  ASP_(converted)_Currency            16947 non-null  object
 38  ASP_(converted)                     13738 non-null  float64
 39  Planned_Delivery_Start_Date         16947 non-null  object
 40  Planned_Delivery_End_Date           16947 non-null  object
 41  Month                               16947 non-null  object
 42  Delivery_Quarter                    16947 non-null  object
 43  Delivery_Year                       16947 non-null  int64
 44  Actual_Delivery_Date                16947 non-null  object
 45  TRF                                 16947 non-null  int64
 46  Total_Amount_Currency               16947 non-null  object
 47  Total_Amount                        16888 non-null  float64
 48  Total_Taxable_Amount_Currency       16947 non-null  object
 49  Total_Taxable_Amount                16947 non-null  float64
 50  Stage                               16947 non-null  object
 51  Prod_Category_A                     16947 non-null  object
dtypes: float64(4), int64(9), object(39)
memory usage: 6.7+ MB

In [48]:
# uso de memoria antes de la conversion de tipos (en KB)
(prospects_stage.memory_usage()/(1024)).sum()

6884.84375

In [77]:
# de ello notamos que hay muchos campos son de tipo category (adem√°s Stage que ya conociamos por la definicion del enunciado)
# de incluso muchos de ellos pueden ser reducidos a tipo boolean.
# luego de una analisis de value_counts (o eventualmente un len del mismo) para comprobar que efectivamente la supocion de que son de este tipo es correcta
# procedemos a la conversion de todos ellos
# excluimos de category fechas, precios y cualquier dato que, pese a poder ser suceptible de ser enumerado comparado con el total de lineas dada las repeticiones
# no consideramos que sea correcto convertirlos a ese tipo tanto para potencial operatoria posterior como para el anaalisis de futuros set de datos

# todo: como interpretamos a los 'None' ?

# category
prospects_stage['Stage'] = prospects_stage['Stage'].astype('category')
prospects_stage['Region'] = prospects_stage['Region'].astype('category')
prospects_stage['Territory'] = prospects_stage['Territory'].astype('category')
prospects_stage['Bureaucratic_Code'] = prospects_stage['Bureaucratic_Code'].astype('category')

prospects_stage['Billing_Country'] = prospects_stage['Bureaucratic_Code'].astype('category')
prospects_stage['Account_Type'] = prospects_stage['Account_Type'].astype('category')
prospects_stage['Opportunity_Type'] = prospects_stage['Opportunity_Type'].astype('category')
prospects_stage['Quote_Type'] = prospects_stage['Quote_Type'].astype('category')
prospects_stage['Delivery_Terms'] = prospects_stage['Delivery_Terms'].astype('category')
prospects_stage['Brand'] = prospects_stage['Brand'].astype('category')
prospects_stage['Product_Type'] = prospects_stage['Product_Type'].astype('category')
prospects_stage['Size'] = prospects_stage['Size'].astype('category')
prospects_stage['Product_Category_B'] = prospects_stage['Product_Category_B'].astype('category')
prospects_stage['Currency'] = prospects_stage['Currency'].astype('category')
prospects_stage['Last_Activity'] = prospects_stage['Last_Activity'].astype('category')
prospects_stage['Last_Modified_By'] = prospects_stage['Last_Modified_By'].astype('category')
prospects_stage['Product_Family'] = prospects_stage['Product_Family'].astype('category')
prospects_stage['Product_Name'] = prospects_stage['Product_Name'].astype('category')
prospects_stage['Prod_Category_A'] = prospects_stage['Prod_Category_A'].astype('category')
prospects_stage['Total_Amount_Currency'] = prospects_stage['Total_Amount_Currency'].astype('category')
prospects_stage['Total_Taxable_Amount_Currency'] = prospects_stage['Total_Taxable_Amount_Currency'].astype('category')
prospects_stage['TRF'] = prospects_stage['TRF'].astype('category')

prospects_stage['Delivery_Quarter'] = prospects_stage['Delivery_Quarter'].astype('category')

# boolean
prospects_stage['Pricing, Delivery_Terms_Quote_Appr'] = prospects_stage['Pricing, Delivery_Terms_Quote_Appr'].astype('bool')
prospects_stage['Pricing, Delivery_Terms_Approved'] = prospects_stage['Pricing, Delivery_Terms_Quote_Appr'].astype('bool')
prospects_stage['Bureaucratic_Code_0_Approval'] = prospects_stage['Bureaucratic_Code_0_Approval'].astype('bool')
prospects_stage['Bureaucratic_Code_0_Approved'] = prospects_stage['Bureaucratic_Code_0_Approved'].astype('bool')

# todo: este especificamenret solo tiene el valor 0... es mejor usar category?
prospects_stage['Submitted_for_Approval'] = prospects_stage['Submitted_for_Approval'].astype('bool')

In [78]:
# uso de memoria antes de la conversion de tipos (en KB)
(prospects_stage.memory_usage()/(1024)).sum()

3844.2880859375

In [88]:
print(len(prospects_stage['Product_Type'].value_counts()))
prospects_stage['Product_Type'].value_counts()

# ? Opportunity_Created_Date -> 1020, Price -> 53, Quote_Expiry_Date -> 1003, Last_Modified_Date  <date> -> 650 
#	ASP_Currency ASP	ASP_(converted)_Currency	ASP_(converted)	Planned_Delivery_Start_Date	
# Planned_Delivery_End_Date	Month	Delivery_Quarter	Delivery_Year	Actual_Delivery_Date		
# 	Total_Amount		Total_Taxable_Amount

7

None              15935
Other               515
Product_Type_3      179
Product_Type_1      142
Product_Type_0       94
Product_Type_4       73
Product_Type_2        9
Name: Product_Type, dtype: int64

In [ ]:
# ideas

# visualizar Stage/won Stage/lost en una distribucion simultanea de region y total_amount (con una segmentacion dada)  todas llevadas a la misma moneda (usd?)
# ejemplo con uno de grafico de heat para lo que mas interesa que sera won y otro para lost (comprado al total de operaciones)

# visualizar Stage/won pro tipo de producto y region para saber si existe algun tipo de producto preferido en una region dada